moni/api/urls.py
# api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .api import UserViewSet, ProfileViewSet, ComunidadViewSet, VertienteViewSet, KitViewSet, DatosViewSet

router = DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'profiles', ProfileViewSet)
router.register(r'comunidades', ComunidadViewSet)
router.register(r'vertientes', VertienteViewSet)
router.register(r'kits', KitViewSet)
router.register(r'datos', DatosViewSet)

urlpatterns = [
    path('', include(router.urls)),
]

moni/crud/urls.py
#crud/urls.py

from django.urls import path
from crud.views import *
from .views import MapaGeneral, MapaAutoridad

app_name='crud'

urlpatterns = [
    
    #Selector
    path("selector/", Select.as_view(), name='select'),

    #index
    path("indice/", Indice.as_view(), name='index'),

    #indice general
    path("indiceComunidad/", IndiceCom.as_view(), name='indcom'),
    path("indiceVertiente/", IndiceVert.as_view(), name='indvert'),

    #Listas
    path("lista_comunidad/", ListaComunidad.as_view(), name='listcom'),
    path("lista_vertiente/", ListaVertiente.as_view(), name='listvert'),
    path("lista_usuarios/", ListaUsuarios.as_view(), name='listauser'),
    path("lista_peticiones/", ListaPeticion.as_view(), name='listpet'),
    path("lista_kit/", ListaKit.as_view(), name='listkit'),
    
    #Creación
    path("nueva_comunidad/", NuevaComunidad.as_view(), name='newcom'),
    path("nuevo_user/", NuevoUser.as_view(), name='newuser'),
    path("nueva_vertiente/", NuevaVertiente.as_view(), name='newvert'),
    path("nuevo_kit/", NuevoKit.as_view(), name='newkit'),

    #Actualizacion
    path("actualizacion_usuarios/<int:pk>/", ActualizarUsuario.as_view(), name='updateuser'),
    path("actualizacion_vertientes/<int:pk>/", ActualizarVertiente.as_view(), name='updatevert'),
    path("actualizacion_comunidades/<int:pk>/", ActualizarComunidad.as_view(), name='updatecom'),
    path("actualizacion_kit/<int:pk>/", ActualizarKit.as_view(), name='updatekit'),

    #Eliminación
    path("eliminar_comunidad/<int:pk>/", eliminar_comunidad, name='deletecom'),
    path("eliminar_usuario/<int:pk>/", eliminar_peticion, name='deleteUser'),
    path("eliminar_vertiente/<int:pk>/", eliminar_vertiente, name='deletevert'),
    path("eliminar_kit/<int:pk>/", eliminar_kit, name='deletekit'),

    #Activación
    path("activación/<int:pk>/", activar_estado, name='activaruser'),

    #Activación total
    path("activación_total/", activar_todo, name='active_all'),

    #Desactivación
    path("desactivar/<int:pk>/", desactivar_estado, name='deactuser'),

    #Mapa General
    path("mapa_admin", MapaGeneral.as_view(), name='mapa_general'),
    path("mapa_autoridad/", MapaAutoridad.as_view(), name='mapa_autoridad'),
    #Prueba
    path("prueba/", Prueba.as_view(), name='prueba'),


]

moni/moni/urls.py
from django.contrib import admin
from django.urls import path,include
from nucleo.views import Inicio
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

urlpatterns = [
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/', include('api.urls')),
    path("",Inicio.as_view() ),
    path('admin/', admin.site.urls),
    path("inicio/", include('nucleo.urls')),
    path("administracion/", include('crud.urls')),
    path("evaluacion/", include('evaluacion.urls')),
    path("monitoreo/", include('habitantes.urls')),
    path('mqtt_data/', include('mqtt_data.urls')),    # Incluye las URLs de la app mqtt_data
]

moni/nucleo/urls.py
from django.urls import path  # Importa la función path para definir rutas de URL
from nucleo.views import *  # Importa todas las vistas desde nucleo.views
from crud.views import NuevoUser  # Importa la vista NuevoUser desde crud.views
from nucleo import views  # Importa el módulo views desde nucleo

app_name = 'nucleo'  # Define el espacio de nombres para las URLs de la aplicación

urlpatterns = [
    # Ruta para la vista de revisión
    path("revision/", revision, name='revision'),
    # Ruta para la vista de inicio
    path("", Inicio.as_view(), name='inicio'),
    # Ruta para la vista de inicio de sesión
    path("login/", InicioSesion.as_view(), name='login'),
    # Ruta para la vista de cierre de sesión
    path("logout/", Cerrarsesion.as_view(), name='logout'),
    # Ruta para la vista de registro de usuarios
    path("registro/", Registro.as_view(), name='registro'),
    # Ruta para la vista de recuperación de contraseña
    path("recuperar/contraseña/", ResetPasswordView.as_view(), name='recuperar'),
    # Ruta para la vista de cambio de contraseña con un token
    path("cambio/contraseña/<str:token>", ChangePasswordView.as_view(), name='cambio'),
    # Rutas para la carga masiva de usuarios
    path('users_massive_upload/', views.users_massive_upload, name="users_massive_upload"),
    path('users_massive_upload_save/', views.users_massive_upload_save, name="users_massive_upload_save"),
    path('users_import_file/', views.users_import_file, name="users_import_file"),
    # Rutas para la carga masiva de vertientes
    path('vertiente_massive_upload/', views.vertiente_massive_upload, name="vertiente_massive_upload"),
    path('vertiente_massive_upload_save/', views.vertiente_massive_upload_save, name="vertiente_massive_upload_save"),
    path('vertiente_import_file/', views.vertiente_import_file, name="vertiente_import_file"),
    # Rutas para la carga masiva de kits
    path('kit_massive_upload/', views.kit_massive_upload, name="kit_massive_upload"),
    path('kit_massive_upload_save/', views.kit_massive_upload_save, name="kit_massive_upload_save"),
    path('kit_import_file/', views.kit_import_file, name="kit_import_file"),
    # Rutas para la carga masiva de comunidades
    path('comunity_massive_upload/', views.comunity_massive_upload, name="comunity_massive_upload"),
    path('comunity_massive_upload_save/', views.comunity_massive_upload_save, name="comunity_massive_upload_save"),
    path('comunity_import_file/', views.comunity_import_file, name="comunity_import_file"),
    # Ruta para la vista de selección anidada
    path("anidado/", Select_anidado.as_view(), name='select'),
    # Ruta para la vista del mapa con un ID de objeto
    path("mapa/<int:objecto_id>/", mapa, name='mapa'),
]

moni/crud/views.py
from typing import Any
from django import http
from django.utils import timezone
import smtplib
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView, TemplateView, UpdateView, DeleteView
from django.views.generic.edit import CreateView
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from user.models import User,Profile
from django.urls import reverse, reverse_lazy
from crud.forms import *
import moni.settings as setting
from django.utils.decorators import method_decorator
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect, JsonResponse
from django.template.loader import render_to_string
from django.views.decorators.csrf import csrf_exempt
from user.utils import admin_required, enviar_correo


# Selector admin
@method_decorator([login_required, admin_required], name='dispatch')
class Select(TemplateView):
    """
    Vista para seleccionar opciones específicas para administradores.

    Atributos:
        template_name (str): La plantilla que se va a utilizar.
        context_object_name (str): El nombre del contexto que se va a utilizar.
    """
    template_name = 'select/select.html'
    context_object_name = 'listaUser'
        
#Indice principal
@method_decorator([login_required, admin_required], name='dispatch')
class Indice(TemplateView):
    """
    Vista de índice que requiere autenticación de usuario.
    Esta vista hereda de `TemplateView` y se asegura de que el usuario esté autenticado
    antes de permitir el acceso. Dependiendo del tipo de usuario, se permite o deniega
    el acceso a la plantilla especificada.
    Decoradores:
        @method_decorator(login_required, name='dispatch'): Requiere que el usuario esté autenticado.
    Atributos:
        template_name (str): Ruta de la plantilla HTML a renderizar.
        context_object_name (str): Nombre del contexto que se pasará a la plantilla.
    Métodos:
        get(request, *args, **kwargs): Maneja las solicitudes GET. Verifica el tipo de usuario
        y permite o deniega el acceso a la vista basada en el grupo al que pertenece el usuario.
        Si el usuario pertenece al grupo 'Administrador', se permite el acceso; de lo contrario,
        se redirige al usuario a la página de inicio.
    """
    
    template_name = 'index/index.html'  
    context_object_name = 'listaUser'

###################################USER##################################
#Indice para User
@method_decorator(login_required,name='dispatch')
class IndiceUser(TemplateView):
    """
    Vista basada en clase para mostrar el índice de usuarios.
    Atributos:
    ----------
    template_name : str
        Ruta al archivo de plantilla HTML que se utilizará para renderizar la vista.
    context_object_name : str
        Nombre del contexto que se pasará a la plantilla HTML.
    Métodos heredados:
    ------------------
    get_context_data(**kwargs):
        Método para obtener el contexto adicional que se pasará a la plantilla.
    """
    
    template_name = 'usuario/index/index.html'  
    context_object_name = 'listaUser'
class Prueba(TemplateView):
    """
    Vista basada en clase que hereda de TemplateView para renderizar una plantilla específica.
    Atributos:
    ----------
    template_name : str
        Ruta de la plantilla HTML que se renderizará.
    context_object_name : str
        Nombre del contexto que se pasará a la plantilla.
    Métodos:
    --------
    No se definen métodos adicionales en esta clase.
    """
    
    template_name = 'usuario/new/prueba.html'  
    context_object_name = 'listaUser'


#Vista para crear un nuevo User
@method_decorator([login_required, admin_required], name='dispatch')
class NuevoUser(CreateView):
    """
    Vista para la creación de un nuevo usuario.
    Esta vista utiliza la clase `CreateView` para manejar la creación de un nuevo usuario en el sistema.
    Requiere que el usuario esté autenticado para acceder a esta vista.
    Decoradores:
        @method_decorator(login_required, name='dispatch'): Requiere que el usuario esté autenticado.
    Atributos:
        model (User): Modelo de usuario que se va a crear.
        form_class (UserFormCRUD): Formulario utilizado para la creación del usuario.
        template_name (str): Ruta de la plantilla HTML para la creación del usuario.
    Métodos:
        get_success_url(self):
            Retorna la URL a la que se redirige después de que el formulario se ha enviado correctamente.
        get(self, request, *args, **kwargs):
            Maneja las solicitudes GET. Verifica si el usuario autenticado pertenece al grupo 'Administrador'.
            Si es así, permite el acceso a la vista de creación de usuario. De lo contrario, redirige al inicio.
        form_valid(self, form):
            Maneja el formulario cuando es válido. Establece el campo 'is_active' del usuario en True antes de guardar.
            Retorna la respuesta de la superclase.
    """
    model = User
    form_class = UserFormCRUD
    template_name = 'usuario/new/newUsuario.html'

    def get_success_url(self):
        return reverse('crud:listauser')
    
    def form_valid(self, form):
        # Establece el campo 'is_active' en True
        form.instance.is_active = True
        return super().form_valid(form)

@method_decorator([login_required, admin_required], name='dispatch')
class ListaUsuarios(ListView):
    """
    Vista basada en clase para listar usuarios.
    Atributos:
    ----------
    model : Model
        Especifica el modelo que se desea mostrar en la lista.
    template_name : str
        Nombre de la plantilla a utilizar para renderizar la vista.
    context_object_name : str
        Nombre del contexto que se pasará a la plantilla.
    Métodos:
    --------
    get(request, *args, **kwargs)
        Maneja la solicitud GET para la vista. Verifica el tipo de usuario y 
        permite el acceso solo si el usuario es un 'Administrador'. De lo contrario, 
        redirige al usuario a la página de inicio.
    """
    model = User  # Especifica el modelo que deseas mostrar en la lista
    template_name = 'usuario/lista/listUser.html'  # Nombre de la plantilla a utilizar
    context_object_name = 'listaUsuarios' 


@method_decorator([login_required, admin_required], name='dispatch')
class ActualizarUsuario(UpdateView):
    """
    Vista para actualizar un usuario existente.
    Atributos:
    ----------
    model : User
        Modelo que se va a actualizar.
    form_class : UpdateForm
        Formulario que se utiliza para actualizar el usuario.
    template_name : str
        Ruta de la plantilla HTML que se utiliza para renderizar la vista.
    success_url : str
        URL a la que se redirige después de una actualización exitosa.
    Métodos:
    --------
    form_valid(form):
        Asigna el grupo al usuario basado en el valor seleccionado en el campo "Rol" del formulario.
        Guarda el perfil del usuario y llama al método form_valid del padre.
    get(request, *args, **kwargs):
        Verifica si el usuario actual es un administrador.
        Si es administrador, permite el acceso a la vista.
        Si no es administrador, redirige al usuario a la página de inicio.
    """
    model = User
    form_class = UpdateForm
    template_name = 'usuario/update/updateUser.html'
    success_url = reverse_lazy('crud:listauser')

    def form_valid(self, form):
        # Asigna el grupo basado en el valor seleccionado en el campo "Rol"
        user = form.save(commit=False)
        tipo = form.cleaned_data['tipo']
        if tipo == 'Usuario':
            user.profile.group_id = 2  # Usuario
        elif tipo == 'Autoridad':
            user.profile.group_id = 3  # Autoridad
        elif tipo == 'Administrador':
            user.profile.group_id = 1  # Admin
        user.profile.save()
        return super().form_valid(form)
    

###################################PETICIONES PARA USUARIOS##################################
@method_decorator([login_required, admin_required], name='dispatch')
class ListaPeticion(ListView):
    """
    Vista basada en clases para listar peticiones de usuarios.
    Decoradores:
        @method_decorator(login_required, name='dispatch'): Requiere que el usuario esté autenticado para acceder a la vista.
    Atributos:
        model (User): Especifica el modelo que se desea mostrar en la lista.
        template_name (str): Nombre de la plantilla a utilizar.
        context_object_name (str): Nombre del contexto que se pasará a la plantilla.
    Métodos:
        get(self, request, *args, **kwargs): Maneja las solicitudes GET. Verifica el tipo de usuario y permite el acceso solo si el usuario es un Administrador. Redirige a la página de inicio si el usuario no está autorizado.
    """
    model = User  # Especifica el modelo que deseas mostrar en la lista
    template_name = 'usuario/lista/listPeticiones.html'  # Nombre de la plantilla a utilizar
    context_object_name = 'listaUsuarios' 

def activar_todo(request):
    """
    Activa todas las cuentas de usuario que están desactivadas y envía un correo electrónico de notificación a cada usuario.
    Args:
        request (HttpRequest): La solicitud HTTP que activa la función.
    Funcionalidad:
        - Filtra los usuarios que están desactivados (is_active=False).
        - Para cada usuario desactivado:
            - Activa la cuenta del usuario (is_active=True).
            - Envía un correo electrónico de notificación utilizando las configuraciones de correo electrónico definidas en el proyecto.
            - Guarda los cambios en la base de datos.
        - Redirige a la vista 'crud:listauser' después de activar todas las cuentas.
    Correo Electrónico:
        - Utiliza el servidor SMTP configurado en las configuraciones del proyecto.

moni/crud/templates/index/index.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <title>Gestion Administrador</title>
    <script src="https://cdn.jsdelivr.net/npm/admin-lte@3.1/dist/js/adminlte.min.js"></script>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/interior.css' %}">
    <link rel="stylesheet" href="{% static 'css/nabvar.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <link rel="stylesheet" href="ruta/a/font-awesome.min.css">
    <link rel="icon" href="https://cdn-icons-png.flaticon.com/512/826/826923.png" type="image/png">
</head>
<body>
    {% include "barra_lateral_admin.html" %}
    
    <nav class="navbar">
        <img src="https://cdn-ua.hostingreactor.com/ua_www/cache/wp-content/uploads/2020/12/Logo_svg.svg" alt="Logo" class="logo">
        <div class="navbar-left">
            <span class="hidro-tech">HidroTech</span>
        </div>
        <div class="navbar-center">
            <div class="admin-box">Vista Administrador</div>
        </div>
        <a href="{% url 'crud:select' %}" class="volverr">Volver</a>
        <a href="{% url 'nucleo:logout' %}" class="cerrar-sesion">Cerrar Sesión</a>
    </nav>



    <div class="vertientes-container">
        <div class="vertientes-header2">
            <h1>
                Seleccione qué desea Administrar
            </h1>
        </div>
    <div class="row1">
        <div class="rectangulo rectangulo-verde">
            <div class="contenido-rectangulo">
                <h2><font color="white"><span class="gestion-text">Comunidades</span><br> </font></h2>
                    <i class="fas fa-question-circle incognito-icon" onmouseover="showText('text1')" onmouseout="hideText('text1')"></i>
            </div>
            <div id="text1" class="hidden-text">
                <h3>¿Para que sirve esto?</h3>
                <h4>Aqui puede ver, crear, eliminar o actualizar el registro de las comunidades y cambiarle sus datos si lo encuentra necesario, estos datos incluyen el nombre de la comunidad, su localización y el numero de vertienes que la conforman.</h4>
            </div>
            <a href="{% url 'crud:listcom' %}">
                <i class="bi bi-box-arrow-in-right"></i>
            </a>
        </div>
        <div class="rectangulo rectangulo-verde">
            <div class="contenido-rectangulo">
                <h2><font color="white"><span class="gestion-text">Vertientes</span><br> </font></h2>
                    <i class="fas fa-question-circle incognito-icon" onmouseover="showText('text2')" onmouseout="hideText('text2')"></i>
            </div>
            <div id="text2" class="hidden-text">
                <h3>¿Para que sirve esto?</h3>
                <h4>Aqui puede ver, crear, eliminar o actualizar el registro de las vertientes y cambiarle sus datos si lo encuentra necesario, estos datos incluyen el nombre de la vertiente, su ubicacion y la descripción.</h4>
            </div>
            <a href="{% url 'crud:listvert' %}">
                <i class="bi bi-box-arrow-in-right"></i>
            </a>
        </div>
    </div>
        <div class="row2">
            <div class="rectangulo rectangulo-verde">
                <div class="contenido-rectangulo">
                    <h2><font color="white"><span class="gestion-text">Habitantes</span><br> </font></h2>
                        <i class="fas fa-question-circle incognito-icon" onmouseover="showText('text3')" onmouseout="hideText('text3')"></i>
                </div>
                <div id="text3" class="hidden-text">
                    <h3>¿Para que sirve esto?</h3>
                    <h4>Aqui puede ver, crear, eliminar o actualizar el registro de habitantes creados y cambiarle sus datos si lo encuentra necesario, estos datos incluyen el nombre, edad y el correo de contacto para notificaciones.</h4>
                </div>
                <a href="{% url 'crud:listauser' %}">
                    <i class="bi bi-box-arrow-in-right"></i>
                </a>
            </div>
            <div class="rectangulo rectangulo-verde">
                <div class="contenido-rectangulo">
                    <h2><font color="white"><span class="gestion-text">Solicitudes de registro</span><br> </font></h2>
                        <i class="fas fa-question-circle incognito-icon" onmouseover="showText('text4')" onmouseout="hideText('text4')"></i>
                </div>
                <div id="text4" class="hidden-text">
                    <h3>¿Para que sirve esto?</h3>
                    <h4>Aqui puede ver las solicitudes de registro para aceptarlas o denegarlas según estime conveniente.
                        Recuerde verificar si el solicitante pertenece a la comunidad que dice mencionar</h4>
                </div>
                <a href="{% url 'crud:listpet' %}">
                    <i class="bi bi-box-arrow-in-right"></i>
                </a>
                
            </div>
        </div>
        <div class="row3">
        <div class="rectangulo rectangulo-verde">
            <div class="contenido-rectangulo">
                <h2><font color="white"><span class="gestion-text">Kit</span><br> </font></h2>
                    <i class="fas fa-question-circle incognito-icon" onmouseover="showText('text5')" onmouseout="hideText('text5')"></i>
            </div>
            <div id="text5" class="hidden-text">
                <h3>¿Para que sirve esto?</h3>
                <h4>Aqui puede ver, crear, eliminar o actualizar el registro de Kit's creados y cambiarle sus datos si lo encuentra necesario, estos datos incluyen el modelo, MAC y la vertiente asociada</h4>
            </div>
            <a href="{% url 'crud:listkit' %}">
                <i class="bi bi-box-arrow-in-right"></i>
            </a>
        </div>
    
    <script>
        function showText(textId) {
            var textElement = document.getElementById(textId);
            textElement.style.display = 'block';
        }

        function hideText(textId) {
            var textElement = document.getElementById(textId);
            textElement.style.display = 'none';
        }
    </script>
</body>
</html>