moni/api/urls.py
# api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .api import UserViewSet, ProfileViewSet, ComunidadViewSet, VertienteViewSet, KitViewSet, DatosViewSet

router = DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'profiles', ProfileViewSet)
router.register(r'comunidades', ComunidadViewSet)
router.register(r'vertientes', VertienteViewSet)
router.register(r'kits', KitViewSet)
router.register(r'datos', DatosViewSet)

urlpatterns = [
    path('', include(router.urls)),
]

moni/crud/urls.py
#crud/urls.py

from django.urls import path
from crud.views import *
from .views import MapaGeneral, MapaAutoridad

app_name='crud'

urlpatterns = [
    
    #Selector
    path("selector/", Select.as_view(), name='select'),

    #index
    path("indice/", Indice.as_view(), name='index'),

    #indice general
    path("indiceComunidad/", IndiceCom.as_view(), name='indcom'),
    path("indiceVertiente/", IndiceVert.as_view(), name='indvert'),

    #Listas
    path("lista_comunidad/", ListaComunidad.as_view(), name='listcom'),
    path("lista_vertiente/", ListaVertiente.as_view(), name='listvert'),
    path("lista_usuarios/", ListaUsuarios.as_view(), name='listauser'),
    path("lista_peticiones/", ListaPeticion.as_view(), name='listpet'),
    path("lista_kit/", ListaKit.as_view(), name='listkit'),
    
    #Creación
    path("nueva_comunidad/", NuevaComunidad.as_view(), name='newcom'),
    path("nuevo_user/", NuevoUser.as_view(), name='newuser'),
    path("nueva_vertiente/", NuevaVertiente.as_view(), name='newvert'),
    path("nuevo_kit/", NuevoKit.as_view(), name='newkit'),

    #Actualizacion
    path("actualizacion_usuarios/<int:pk>/", ActualizarUsuario.as_view(), name='updateuser'),
    path("actualizacion_vertientes/<int:pk>/", ActualizarVertiente.as_view(), name='updatevert'),
    path("actualizacion_comunidades/<int:pk>/", ActualizarComunidad.as_view(), name='updatecom'),
    path("actualizacion_kit/<int:pk>/", ActualizarKit.as_view(), name='updatekit'),

    #Eliminación
    path("eliminar_comunidad/<int:pk>/", eliminar_comunidad, name='deletecom'),
    path("eliminar_usuario/<int:pk>/", eliminar_peticion, name='deleteUser'),
    path("eliminar_vertiente/<int:pk>/", eliminar_vertiente, name='deletevert'),
    path("eliminar_kit/<int:pk>/", eliminar_kit, name='deletekit'),

    #Activación
    path("activación/<int:pk>/", activar_estado, name='activaruser'),

    #Activación total
    path("activación_total/", activar_todo, name='active_all'),

    #Desactivación
    path("desactivar/<int:pk>/", desactivar_estado, name='deactuser'),

    #Mapa General
    path("mapa_admin", MapaGeneral.as_view(), name='mapa_general'),
    path("mapa_autoridad/", MapaAutoridad.as_view(), name='mapa_autoridad'),
    #Prueba
    path("prueba/", Prueba.as_view(), name='prueba'),


]

moni/habitantes/urls.py
from django.urls import path, include  # Importa la función path para definir rutas de URL
from habitantes.views import *  # Importa todas las vistas desde habitantes.views
from habitantes import views  # Importa el módulo views desde habitantes

app_name = 'habi'  # Define el espacio de nombres para las URLs de la aplicación

urlpatterns = [
    # Selector de comunidades para el admin
    path("lista_vertientes/<int:object_id>/", filtro, name='listvert'),  # Ruta para filtrar vertientes por comunidad
    path("vertientes_admin/<int:objecto_id>/", revision_admin, name='verti_admin'),  # Ruta para la revisión de vertientes por el admin
    path("vertiente/<int:objecto_id>/<int:objecto_id_2>/", revision, name='verti'),  # Ruta para la revisión de una vertiente específica
    path("detector/", detector, name='detect'),  # Ruta para el detector
    path("vertientes/<int:objecto_id>/", revision_autoridad, name='verti_autoridad'),  # Ruta para la revisión de vertientes por la autoridad

    # Gráficos
    path('grafico/<str:tipo_grafico>/<int:vertiente_id>/', views.grafico_generico, name='grafico_generico'),  # Ruta para generar gráficos genéricos
    path('miPerfil/<int:pk>/', ActualizarPerfil.as_view(), name='miPerfil'),  # Ruta para actualizar el perfil del usuario

    # URL para actualización automática de los datos de vertientes
    path('sse_datos/<int:objecto_id>/', views.sse_datos, name='sse_datos'),  # Ruta para la actualización automática de datos de vertientes
    path('sse_grafico/<int:vertiente_id>/<str:tipo_grafico>/<str:date_range>/', views.sse_grafico, name='sse_grafico'),  # Ruta para la actualización automática de gráficos
]

moni/moni/urls.py
from django.contrib import admin
from django.urls import path,include
from nucleo.views import Inicio
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

urlpatterns = [
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/', include('api.urls')),
    path("",Inicio.as_view() ),
    path('admin/', admin.site.urls),
    path("inicio/", include('nucleo.urls')),
    path("administracion/", include('crud.urls')),
    path("evaluacion/", include('evaluacion.urls')),
    path("monitoreo/", include('habitantes.urls')),
    path('mqtt_data/', include('mqtt_data.urls')),    # Incluye las URLs de la app mqtt_data
]

moni/nucleo/urls.py
from django.urls import path  # Importa la función path para definir rutas de URL
from nucleo.views import *  # Importa todas las vistas desde nucleo.views
from crud.views import NuevoUser  # Importa la vista NuevoUser desde crud.views
from nucleo import views  # Importa el módulo views desde nucleo

app_name = 'nucleo'  # Define el espacio de nombres para las URLs de la aplicación

urlpatterns = [
    # Ruta para la vista de revisión
    path("revision/", revision, name='revision'),
    # Ruta para la vista de inicio
    path("", Inicio.as_view(), name='inicio'),
    # Ruta para la vista de inicio de sesión
    path("login/", InicioSesion.as_view(), name='login'),
    # Ruta para la vista de cierre de sesión
    path("logout/", Cerrarsesion.as_view(), name='logout'),
    # Ruta para la vista de registro de usuarios
    path("registro/", Registro.as_view(), name='registro'),
    # Ruta para la vista de recuperación de contraseña
    path("recuperar/contraseña/", ResetPasswordView.as_view(), name='recuperar'),
    # Ruta para la vista de cambio de contraseña con un token
    path("cambio/contraseña/<str:token>", ChangePasswordView.as_view(), name='cambio'),
    # Rutas para la carga masiva de usuarios
    path('users_massive_upload/', views.users_massive_upload, name="users_massive_upload"),
    path('users_massive_upload_save/', views.users_massive_upload_save, name="users_massive_upload_save"),
    path('users_import_file/', views.users_import_file, name="users_import_file"),
    # Rutas para la carga masiva de vertientes
    path('vertiente_massive_upload/', views.vertiente_massive_upload, name="vertiente_massive_upload"),
    path('vertiente_massive_upload_save/', views.vertiente_massive_upload_save, name="vertiente_massive_upload_save"),
    path('vertiente_import_file/', views.vertiente_import_file, name="vertiente_import_file"),
    # Rutas para la carga masiva de kits
    path('kit_massive_upload/', views.kit_massive_upload, name="kit_massive_upload"),
    path('kit_massive_upload_save/', views.kit_massive_upload_save, name="kit_massive_upload_save"),
    path('kit_import_file/', views.kit_import_file, name="kit_import_file"),
    # Rutas para la carga masiva de comunidades
    path('comunity_massive_upload/', views.comunity_massive_upload, name="comunity_massive_upload"),
    path('comunity_massive_upload_save/', views.comunity_massive_upload_save, name="comunity_massive_upload_save"),
    path('comunity_import_file/', views.comunity_import_file, name="comunity_import_file"),
    # Ruta para la vista de selección anidada
    path("anidado/", Select_anidado.as_view(), name='select'),
    # Ruta para la vista del mapa con un ID de objeto
    path("mapa/<int:objecto_id>/", mapa, name='mapa'),
]

moni/nucleo/models.py
from django.db import models  # Importa el módulo models de Django para definir modelos
from datetime import datetime  # Importa la clase datetime para trabajar con fechas y horas

# Define el modelo comunidad
class comunidad(models.Model):
    nombre = models.CharField(max_length=150, verbose_name='Nombre')  # Nombre de la comunidad
    encargado = models.CharField(max_length=100, verbose_name='Encargado', null=False, blank=False)  # Nombre del encargado
    contacto_encargado = models.CharField(max_length=100, verbose_name='Contacto del encargado', null=False, blank=False)  # Contacto del encargado
    vertientes = models.PositiveIntegerField(default=0, null=True, blank=True)  # Número de vertientes
    ubicación = models.CharField(max_length=200, verbose_name='Ubicación', null=True, blank=True)  # Ubicación de la comunidad
    latitud = models.FloatField(null=True, blank=True)  # Latitud de la comunidad
    longitud = models.FloatField(null=True, blank=True)  # Longitud de la comunidad

    def __str__(self):
        return self.nombre  # Representación en cadena del modelo

    class Meta:
        verbose_name = 'Comunidad'  # Nombre singular del modelo
        verbose_name_plural = 'Comunidades'  # Nombre plural del modelo
        db_table = 'comunidad'  # Nombre de la tabla en la base de datos
        ordering = ['id']  # Ordenamiento por defecto

# Define el modelo vertiente
class vertiente(models.Model):
    nombre = models.CharField(max_length=150, verbose_name='Nombre')  # Nombre de la vertiente
    desc = models.CharField(max_length=250, verbose_name='Descripcion', null=True, blank=True)  # Descripción de la vertiente
    ubicación = models.CharField(max_length=200, verbose_name='Ubicación', null=True, blank=True)  # Ubicación de la vertiente
    latitud = models.FloatField(null=True, blank=True)  # Latitud de la vertiente
    longitud = models.FloatField(null=True, blank=True)  # Longitud de la vertiente

    comunidad = models.ForeignKey(comunidad, on_delete=models.SET_NULL, null=True)  # Relación con el modelo comunidad

    def __str__(self):
        return self.nombre  # Representación en cadena del modelo

    class Meta:
        verbose_name = 'Vertiente'  # Nombre singular del modelo
        verbose_name_plural = 'Vertientes'  # Nombre plural del modelo
        db_table = 'vertiente'  # Nombre de la tabla en la base de datos
        ordering = ['id']  # Ordenamiento por defecto

# Define el modelo kit
class kit(models.Model):
    modelo = models.IntegerField(default=0)  # Modelo del kit
    mac = models.CharField(max_length=25, verbose_name='Direccion MAC', null=True, blank=True)  # Dirección MAC del kit
    is_active = models.BooleanField(default=False)  # Estado de activación del kit
    created_at = models.DateTimeField(auto_now_add=True)  # Fecha de creación del kit
    modified_at = models.DateTimeField(auto_now=True)  # Fecha de última modificación del kit

    vertiente = models.ForeignKey(vertiente, on_delete=models.SET_NULL, null=True)  # Relación con el modelo vertiente

    def __str__(self):
        return str(self.modelo)  # Representación en cadena del modelo

    class Meta:
        verbose_name = 'Kit'  # Nombre singular del modelo
        verbose_name_plural = 'Kits'  # Nombre plural del modelo
        db_table = 'Kit'  # Nombre de la tabla en la base de datos
        ordering = ['id']  # Ordenamiento por defecto

# Define el modelo datos
class datos(models.Model):
    caudal = models.FloatField(default=0)  # Caudal de la vertiente
    pH = models.FloatField(default=0)  # pH de la vertiente
    conductividad = models.FloatField(default=0)  # Conductividad de la vertiente
    turbiedad = models.FloatField(default=0)  # Turbiedad de la vertiente
    temperatura = models.FloatField(default=0)  # Temperatura de la vertiente
    humedad = models.FloatField(default=0)  # Humedad de la vertiente
    fecha = models.DateTimeField(auto_now=True)  # Fecha de registro de los datos

    mac = models.CharField(max_length=25, verbose_name='Direccion MAC', null=True, blank=True)  # Dirección MAC del kit
    kit = models.ForeignKey(kit, on_delete=models.SET_NULL, null=True)  # Relación con el modelo kit
    vertiente = models.ForeignKey(vertiente, on_delete=models.SET_NULL, null=True)  # Relación con el modelo vertiente

    class Meta:
        verbose_name = 'Dato'  # Nombre singular del modelo
        verbose_name_plural = 'Datos'  # Nombre plural del modelo
        db_table = 'datos'  # Nombre de la tabla en la base de datos
        ordering = ['id']  # Ordenamiento por defecto

moni/nucleo/forms.py
from django.forms import *  # Importa todas las clases y funciones del módulo django.forms
from django import forms  # Importa el módulo forms de Django
from nucleo.models import comunidad, vertiente  # Importa los modelos comunidad y vertiente desde nucleo.models
from user.models import User  # Importa el modelo User desde user.models

class TestForm(Form):
    """
    Formulario de prueba que incluye campos para seleccionar una comunidad y una vertiente.
    """
    comunidad = ModelChoiceField(
        queryset=comunidad.objects.all(),  # Consulta para obtener todas las comunidades
        widget=Select(
            attrs={
                'class': 'form-control'  # Clase CSS para el campo de selección de comunidad
            }
        )
    )
    vertiente = ModelChoiceField(
        queryset=vertiente.objects.none(),  # Consulta vacía para las vertientes, se llenará dinámicamente
        widget=Select(
            attrs={
                'class': 'form-control'  # Clase CSS para el campo de selección de vertiente
            }
        )
    )

class ResetPasswordForm(forms.Form):
    """
    Formulario para restablecer la contraseña de un usuario.
    """
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Ingrese username',  # Texto de marcador de posición
                'class': 'form-control',  # Clase CSS para el campo de entrada de texto
                'autocomplete': 'off'  # Desactiva el autocompletado del navegador
            }
        )
    )

    def clean(self):
        """
        Valida que el usuario exista en la base de datos.
        """
        cleaned = super().clean()
        if not User.objects.filter(username=cleaned['username']).exists():
            raise forms.ValidationError('El usuario no existe')  # Lanza un error si el usuario no existe
        return cleaned
    
    def get_user(self):
        """
        Obtiene el usuario basado en el nombre de usuario proporcionado.
        """
        username = self.cleaned_data.get('username')
        return User.objects.get(username=username)  # Devuelve el usuario correspondiente

class ChangePasswordForm(forms.Form):
    """
    Formulario para cambiar la contraseña de un usuario.
    """
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                'placeholder': 'nueva contraseña',  # Texto de marcador de posición
                'class': 'form-control',  # Clase CSS para el campo de entrada de contraseña
                'autocomplete': 'off'  # Desactiva el autocompletado del navegador
            }
        )
    )

    confirmPassword = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                'placeholder': 'Repita la contraseña',  # Texto de marcador de posición
                'class': 'form-control',  # Clase CSS para el campo de entrada de confirmación de contraseña
                'autocomplete': 'off'  # Desactiva el autocompletado del navegador
            }
        )
    )

    def clean(self):
        """
        Valida que las contraseñas coincidan.
        """
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        confirmPassword = cleaned_data.get('confirmPassword')

        if password and confirmPassword:
            if password != confirmPassword:
                self.add_error('confirmPassword', 'Las contraseñas deben ser iguales')  # Agrega un error si las contraseñas no coinciden
            else:
                self.success_message = "Su contraseña se ha cambiado correctamente."  # Mensaje de éxito si las contraseñas coinciden

        return cleaned_data

moni/nucleo/templates/change.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <link rel="icon" href="https://cdn-icons-png.flaticon.com/512/826/826923.png" type="image/png">
    <link rel="stylesheet" href="{% static 'css/exterior.css' %}">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Recuperar Contraseña</title>
    <style>
        .error { color: red; } 
        .messages { margin-bottom: 15px; } 
    </style>
</head>
<body>
    <nav class="navbar">
        <img src="https://cdn-ua.hostingreactor.com/ua_www/cache/wp-content/uploads/2020/12/Logo_svg.svg" alt="Logo" class="logo">
        <ul class="navbar-nav">
        </ul>
        <a href="{% url 'nucleo:login' %}" class="cerrar-sesion">Volver</a>
    </nav>

    <!-- Bloque para mostrar mensajes de Django -->
    {% if messages %}
        <div class="messages">
            {% for message in messages %}
                <div class="{{ message.tags }}">{{ message }}</div>
            {% endfor %}
        </div>
        
    {% endif %}
    <main>
        <div id="contenedorseña">
            <div id="formulario">
                <h2 id="tituloseña">Cambio de Contraseña</h2>
                <form method="post">
                    {% csrf_token %}
                    <div style="display: flex; justify-content: space-between;">
                        <div>
                            {{ form.password }}
                            {% if form.password.errors %}
                                <div class="error">{{ form.password.errors.as_text }}</div>
                            {% endif %}
                        </div>
                        <div style="margin-left: 10px;">
                            {{ form.confirmPassword }}
                            {% if form.confirmPassword.errors %}
                                <div class="error">{{ form.confirmPassword.errors.as_text }}</div>
                            {% endif %}
                        </div>
                    </div>
                    {% if form.non_field_errors %}
                        <div class="error">
                            {{ form.non_field_errors.as_text }}
                        </div>
                    {% endif %}
                    <p id="recordatorio">Proporcione la nueva contraseña que desea utilizar para la actualización.</p>
                    <button id="botonRecuperar" type="submit">Recuperar</button>
                </form>
            </div>
        </div>
    </main>

    <footer class="footer">
        <p>&copy; 2023 U. Autónoma. Todos los derechos reservados.</p>
    </footer>
</body>
</html>

moni/nucleo/templates/comunity_massive_upload.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
    <head>
        <script src="https://cdn.jsdelivr.net/npm/admin-lte@3.1/dist/js/adminlte.min.js"></script>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'css/interior.css' %}">
        <link rel="stylesheet" href="{% static 'css/nabvar.css' %}">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
        <link href="https://cdn.datatables.net/v/dt/dt-1.13.6/datatables.min.css" rel="stylesheet">
        <script src="https://code.jquery.com/jquery-3.7.0.js"></script>
        <script src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js"></script>
        <link rel="icon" href="https://cdn-icons-png.flaticon.com/512/826/826923.png" type="image/png">
        <title>Carga Masiva de Comunidades</title>
    </head>
    <body>

    {% include "barra_lateral_admin.html" %}

        <nav class="navbar">
            <img src="https://cdn-ua.hostingreactor.com/ua_www/cache/wp-content/uploads/2020/12/Logo_svg.svg" alt="Logo" class="logo">
            <div class="navbar-left">
                <span class="hidro-tech">HidroTech</span>
            </div>
            <div class="navbar-center">
                <div class="admin-box">Vista Administrador</div>
            </div>
            <a href="{% url 'crud:listcom' %}" class="volverr"style=" margin-top:-1px">Volver</a>
            <a href="{% url 'nucleo:logout' %}" class="cerrar-sesion">Cerrar Sesión</a>
        </nav>
{% block content %}
{% block extrahead %}
{% endblock %}
<main role="main">
    <div class="container col-12 mt-3">
        <div class="col-12  mt-3 border">
            <h1>Carga Masiva de Comunidades</h1>
            {% if error_message %}
            <h3> 
    {{ error_message }}
    
</h3>
<a href="{% url 'crud:listcom' %}" class="accederr">Volver</a>
{% endif %}
            {%if profiles.group_id == 1 %}
            <div class="col-12">
                <form action="{% url 'nucleo:comunity_massive_upload_save' %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-12 col-sm-6 mb-3">
                            <input type="file" name="myfile" class="form-control border border-danger" required>
                        </div>
                        <div class="col-12 col-sm-3">
                            <button class="accederr"type="submit">Cargar</button>
                        </div>
                    </div>
                </form>
            </div>
            <div class="col-12 mt-3 border">
                <h2>Descargar archivo de importación</h2>
                <a href="{% url 'nucleo:comunity_import_file' %}" class="accederr">Descargar</a>
            </div>
            {% endif %}
        </div>
    </div>
</main>
{% endblock %}

moni/nucleo/templates/kit_massive_upload.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
    <head>
        <script src="https://cdn.jsdelivr.net/npm/admin-lte@3.1/dist/js/adminlte.min.js"></script>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'css/interior.css' %}">
        <link rel="stylesheet" href="{% static 'css/nabvar.css' %}">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
        <link href="https://cdn.datatables.net/v/dt/dt-1.13.6/datatables.min.css" rel="stylesheet">
        <script src="https://code.jquery.com/jquery-3.7.0.js"></script>
        <script src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js"></script>
        <link rel="icon" href="https://cdn-icons-png.flaticon.com/512/826/826923.png" type="image/png">
        <title>Carga Masiva de Kits</title>
    </head>
    <body>

    {% include "barra_lateral_admin.html" %}

        <nav class="navbar">
            <img src="https://cdn-ua.hostingreactor.com/ua_www/cache/wp-content/uploads/2020/12/Logo_svg.svg" alt="Logo" class="logo">
            <div class="navbar-left">
                <span class="hidro-tech">HidroTech</span>
            </div>
            <div class="navbar-center">
                <div class="admin-box">Vista Administrador</div>
            </div>
            <a href="{% url 'crud:listkit' %}" class="volverr"style=" margin-top:-1px">Volver</a>
            <a href="{% url 'nucleo:logout' %}" class="cerrar-sesion">Cerrar Sesión</a>
        </nav>
{% block content %}
{% block extrahead %}
{% endblock %}
<main role="main">
    <div class="container col-12 mt-3">
        <div class="col-12  mt-3 border">
            <h1>Carga Masiva de Kits</h1>
            {% if error_message %}
            <h3> 
    {{ error_message }}
    
</h3>
<a href="{% url 'crud:listkit' %}" class="accederr">Volver</a>
{% endif %}
            {%if profiles.group_id == 1 %}
            <div class="col-12">
                <form action="{% url 'nucleo:kit_massive_upload_save' %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-12 col-sm-6 mb-3">
                            <input type="file" name="myfile" class="form-control border border-danger" required>
                        </div>
                        <div class="col-12 col-sm-3">
                            <button  class="accederr"type="submit">Cargar</button >
                        </div>
                    </div>
                </form>
            </div>

            <div class="col-12 mt-3 border">
                <h2>Descargar archivo de importación</h2>
                <a href="{% url 'nucleo:kit_import_file' %}" class="accederr">Descargar</a>
            </div>
            {% endif %}
        </div>
    </div>
                
</main>
{% endblock %}

moni/nucleo/templates/users_massive_upload.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
    <head>
        <script src="https://cdn.jsdelivr.net/npm/admin-lte@3.1/dist/js/adminlte.min.js"></script>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'css/interior.css' %}">
        <link rel="stylesheet" href="{% static 'css/nabvar.css' %}">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
        <link href="https://cdn.datatables.net/v/dt/dt-1.13.6/datatables.min.css" rel="stylesheet">
        <script src="https://code.jquery.com/jquery-3.7.0.js"></script>
        <script src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js"></script>
        <link rel="icon" href="https://cdn-icons-png.flaticon.com/512/826/826923.png" type="image/png">
        <title>Carga Masiva de Habitantes</title>
    </head>
    <body>

    {% include "barra_lateral_admin.html" %}

        <nav class="navbar">
            <img src="https://cdn-ua.hostingreactor.com/ua_www/cache/wp-content/uploads/2020/12/Logo_svg.svg" alt="Logo" class="logo">
            <div class="navbar-left">
                <span class="hidro-tech">HidroTech</span>
            </div>
            <div class="navbar-center">
                <div class="admin-box">Vista Administrador</div>
            </div>
            <a href="{% url 'crud:listauser' %}" class="volverr"style=" margin-top:-1px">Volver</a>
            <a href="{% url 'nucleo:logout' %}" class="cerrar-sesion">Cerrar Sesión</a>
        </nav>
{% block content %}
{% block extrahead %}
{% endblock %}
<main role="main">
    <div class="container col-12 mt-3">
        <div class="col-12  mt-3 border">
            <h1>Carga Masiva de Habitantes</h1>
            {% if error_message %}
            <h3> 
    {{ error_message }}
    
</h3>
<a href="{% url 'crud:listauser' %}" class="accederr">Volver</a>
{% endif %}
            {%if profiles.group_id == 1 %}
            <div class="col-12">
                <form action="{% url 'nucleo:users_massive_upload_save' %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-12 col-sm-6 mb-3">
                            <input type="file" name="myfile" class="form-control border border-danger" required>
                        </div>
                        <div class="col-12 col-sm-3">
                            <button class="accederr"type="submit">Cargar</button>
                        </div>
                    </div>
                </form>
            </div>
            <div class="col-12 mt-3 border">
                <h2>Descargar archivo de importación</h2>
                <a href="{% url 'nucleo:users_import_file' %}" class="accederr">Descargar</a>
            </div>
            {% endif %}
        </div>
    </div>
</main>
{% endblock %}