moni/api/urls.py
# api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .api import UserViewSet, ProfileViewSet, ComunidadViewSet, VertienteViewSet, KitViewSet, DatosViewSet

router = DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'profiles', ProfileViewSet)
router.register(r'comunidades', ComunidadViewSet)
router.register(r'vertientes', VertienteViewSet)
router.register(r'kits', KitViewSet)
router.register(r'datos', DatosViewSet)

urlpatterns = [
    path('', include(router.urls)),
]

moni/crud/urls.py
#crud/urls.py

from django.urls import path
from crud.views import *
from .views import MapaGeneral, MapaAutoridad

app_name='crud'

urlpatterns = [
    
    #Selector
    path("selector/", Select.as_view(), name='select'),

    #index
    path("indice/", Indice.as_view(), name='index'),

    #indice general
    path("indiceComunidad/", IndiceCom.as_view(), name='indcom'),
    path("indiceVertiente/", IndiceVert.as_view(), name='indvert'),

    #Listas
    path("lista_comunidad/", ListaComunidad.as_view(), name='listcom'),
    path("lista_vertiente/", ListaVertiente.as_view(), name='listvert'),
    path("lista_usuarios/", ListaUsuarios.as_view(), name='listauser'),
    path("lista_peticiones/", ListaPeticion.as_view(), name='listpet'),
    path("lista_kit/", ListaKit.as_view(), name='listkit'),
    
    #Creación
    path("nueva_comunidad/", NuevaComunidad.as_view(), name='newcom'),
    path("nuevo_user/", NuevoUser.as_view(), name='newuser'),
    path("nueva_vertiente/", NuevaVertiente.as_view(), name='newvert'),
    path("nuevo_kit/", NuevoKit.as_view(), name='newkit'),

    #Actualizacion
    path("actualizacion_usuarios/<int:pk>/", ActualizarUsuario.as_view(), name='updateuser'),
    path("actualizacion_vertientes/<int:pk>/", ActualizarVertiente.as_view(), name='updatevert'),
    path("actualizacion_comunidades/<int:pk>/", ActualizarComunidad.as_view(), name='updatecom'),
    path("actualizacion_kit/<int:pk>/", ActualizarKit.as_view(), name='updatekit'),

    #Eliminación
    path("eliminar_comunidad/<int:pk>/", eliminar_comunidad, name='deletecom'),
    path("eliminar_usuario/<int:pk>/", eliminar_peticion, name='deleteUser'),
    path("eliminar_vertiente/<int:pk>/", eliminar_vertiente, name='deletevert'),
    path("eliminar_kit/<int:pk>/", eliminar_kit, name='deletekit'),

    #Activación
    path("activación/<int:pk>/", activar_estado, name='activaruser'),

    #Activación total
    path("activación_total/", activar_todo, name='active_all'),

    #Desactivación
    path("desactivar/<int:pk>/", desactivar_estado, name='deactuser'),

    #Mapa General
    path("mapa_admin", MapaGeneral.as_view(), name='mapa_general'),
    path("mapa_autoridad/", MapaAutoridad.as_view(), name='mapa_autoridad'),
    #Prueba
    path("prueba/", Prueba.as_view(), name='prueba'),


]

moni/moni/urls.py
from django.contrib import admin
from django.urls import path,include
from nucleo.views import Inicio
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

urlpatterns = [
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/', include('api.urls')),
    path("",Inicio.as_view() ),
    path('admin/', admin.site.urls),
    path("inicio/", include('nucleo.urls')),
    path("administracion/", include('crud.urls')),
    path("evaluacion/", include('evaluacion.urls')),
    path("monitoreo/", include('habitantes.urls')),
    path('mqtt_data/', include('mqtt_data.urls')),    # Incluye las URLs de la app mqtt_data
]

moni/nucleo/urls.py
from django.urls import path  # Importa la función path para definir rutas de URL
from nucleo.views import *  # Importa todas las vistas desde nucleo.views
from crud.views import NuevoUser  # Importa la vista NuevoUser desde crud.views
from nucleo import views  # Importa el módulo views desde nucleo

app_name = 'nucleo'  # Define el espacio de nombres para las URLs de la aplicación

urlpatterns = [
    # Ruta para la vista de revisión
    path("revision/", revision, name='revision'),
    # Ruta para la vista de inicio
    path("", Inicio.as_view(), name='inicio'),
    # Ruta para la vista de inicio de sesión
    path("login/", InicioSesion.as_view(), name='login'),
    # Ruta para la vista de cierre de sesión
    path("logout/", Cerrarsesion.as_view(), name='logout'),
    # Ruta para la vista de registro de usuarios
    path("registro/", Registro.as_view(), name='registro'),
    # Ruta para la vista de recuperación de contraseña
    path("recuperar/contraseña/", ResetPasswordView.as_view(), name='recuperar'),
    # Ruta para la vista de cambio de contraseña con un token
    path("cambio/contraseña/<str:token>", ChangePasswordView.as_view(), name='cambio'),
    # Rutas para la carga masiva de usuarios
    path('users_massive_upload/', views.users_massive_upload, name="users_massive_upload"),
    path('users_massive_upload_save/', views.users_massive_upload_save, name="users_massive_upload_save"),
    path('users_import_file/', views.users_import_file, name="users_import_file"),
    # Rutas para la carga masiva de vertientes
    path('vertiente_massive_upload/', views.vertiente_massive_upload, name="vertiente_massive_upload"),
    path('vertiente_massive_upload_save/', views.vertiente_massive_upload_save, name="vertiente_massive_upload_save"),
    path('vertiente_import_file/', views.vertiente_import_file, name="vertiente_import_file"),
    # Rutas para la carga masiva de kits
    path('kit_massive_upload/', views.kit_massive_upload, name="kit_massive_upload"),
    path('kit_massive_upload_save/', views.kit_massive_upload_save, name="kit_massive_upload_save"),
    path('kit_import_file/', views.kit_import_file, name="kit_import_file"),
    # Rutas para la carga masiva de comunidades
    path('comunity_massive_upload/', views.comunity_massive_upload, name="comunity_massive_upload"),
    path('comunity_massive_upload_save/', views.comunity_massive_upload_save, name="comunity_massive_upload_save"),
    path('comunity_import_file/', views.comunity_import_file, name="comunity_import_file"),
    # Ruta para la vista de selección anidada
    path("anidado/", Select_anidado.as_view(), name='select'),
    # Ruta para la vista del mapa con un ID de objeto
    path("mapa/<int:objecto_id>/", mapa, name='mapa'),
]

moni/crud/forms.py
# crud/forms.py
from django.forms import *
from django.contrib.auth.forms import UserCreationForm
from nucleo.models import *
from user.models import User,Profile
from django import forms
from django.core import validators
from django.core.exceptions import ValidationError

class ComunidadForm(ModelForm):
    class Meta:
        model= comunidad
        fields='__all__'
        exclude=['vertientes']

class VertienteForm(ModelForm):
    class Meta:
        model= vertiente
        fields=['nombre','desc','ubicación','comunidad','latitud','longitud']
        
class KitForm(ModelForm):

    comunidad=ModelChoiceField(
        queryset=comunidad.objects.all(),
        widget=Select(
            attrs={
                'class':'form-control'

    }))

    vertiente=ModelChoiceField(
        queryset=vertiente.objects.none(),
        widget=Select(
            attrs={
                'class':'form-control'

    }))
    
    class Meta:
        model= kit
        fields = ['modelo', 'mac', 'is_active', 'comunidad', 'vertiente']

def validate_rut(value):
        value = value.replace('.', '')  # Elimina puntos
        value = value.replace('-', '')  # Elimina guiones
        
        if len(value)>9:
            raise ValidationError('RUT inválido, ingrese un RUT de 9 digitos maximo')

        if not value[:-1].isdigit() or value[-1].lower() not in '0123456789k':
            raise ValidationError('Rut inválido')

class UserForm(ModelForm):
    email = forms.CharField(validators=[validators.EmailValidator(message="El correo electrónico debe ser válido.")])
    confirmar_contraseña = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model= User
        fields=['username','first_name','last_name','email',
                'edad','gender','comunidad','password']
        labels={
            'username':'RUT',
            'first_name':'Nombre',
            'last_name':'Apellido',
            'email':'Correo electronico',
            'edad':'Rango de edad',
            'gender':'Género',
            'password':'Contraseña',
        }
        help_texts = {
            'username': '',
            'first_name': '',
            'last_name': '',
            'email': '',
            'edad': '',
            'password': '*Le recomendamos escribir una contraseña sencilla, como pueden ser, los últimos 4 digitos de su RUT.',
        }
        widgets={
            'username':TextInput( 
                attrs={
                    'class':'form-control',
                    'placeholder':'Escriba su rut con el formato: (203627904)'

                }
            ), 
            'first_name':TextInput( 
                attrs={
                    'class':'form-control',
                    'placeholder':'Pedro'

                }
            ),
            'last_name':TextInput( 
                attrs={
                    'class':'form-control',
                    'placeholder':'Muñoz'

                }
            ),
            'email':TextInput( 
                attrs={
                    'class':'form-control',
                    'placeholder':'Pedromuñoz@gmail.com'

                }
            ),
            'password':PasswordInput( 
                attrs={
                    'class':'form-control',
                    

                }
            ),
        }
    
    
    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        self.fields['comunidad'].required = True
        self.fields['username'].required = True
        self.fields['first_name'].required = True
        self.fields['last_name'].required = True
        self.fields['edad'].required = True
        self.fields['email'].required = True
        self.fields['gender'].required = True
        self.fields['password'].required = True
    

    def clean_username(self):
        username = self.cleaned_data['username']
        validate_rut(username)  # Llama a la función de validación personalizada
        username = username.replace('.', '')  # Elimina puntos
        username = username.replace('-', '')  # Elimina guiones
        return username
    
    def clean(self):
        cleaned_data = super().clean()
        password1 = cleaned_data.get("password")
        confirmar_contraseña = cleaned_data.get("confirmar_contraseña")

        if password1 != confirmar_contraseña:
            raise forms.ValidationError("Las contraseñas no coinciden")

    def save(self, commit=True):
        data = {}
        form = super()
        if form.is_valid():
            pwd = self.cleaned_data['password']
            u = form.save(commit=False)
            if u.pk is None:
                u.set_password(pwd)
                u.save()  # Save the user first to get a primary key (u.pk)
                
                # Create a Profile instance for the user
                profile = Profile(user=u, group_id=2)
                profile.save()
            else:
                user = User.objects.get(pk=u.pk)
                if user.password != pwd:
                    u.set_password(pwd)
                u.save()
        else:
            data['error'] = form.errors

class UpdateForm(ModelForm):
    ROLES = (
        ('Usuario', 'Usuario'),
        ('Autoridad', 'Autoridad'),
        ('Administrador', 'Administrador')
    )
    email = forms.CharField(validators=[validators.EmailValidator(message="El correo electrónico debe ser válido.")])
    tipo = forms.ChoiceField(choices=ROLES, label='Rol')
    class Meta:
        model= User
        fields=['username','first_name','last_name','email',
                'edad','comunidad','tipo','is_active']
        labels={
            'username':'RUT',
            'first_name':'Nombre',
            'last_name':'Apellido',
            'email':'Correo electrónico',
            'edad':'Edad',
            'is_active':'Estado',
        }
        widgets={
            'username':TextInput( 
                attrs={
                    'class':'form-control',
                    'placeholder':'Escriba su rut con el formato: (203627904)'

                }
            ),
            'first_name':TextInput( 
                attrs={
                    'class':'form-control',
                    'placeholder':'Pedro'

                }
            ),
            'last_name':TextInput( 
                attrs={
                    'class':'form-control',
                    'placeholder':'Muñoz'

                }
            ),
            'email':TextInput( 
                attrs={
                    'class':'form-control',
                    'placeholder':'Pedromuñoz@gmail.com'

                }
            ),
            
            'tipo':TextInput( 
                attrs={
                    'class':'form-control',
                    

                }
            ),
            
        }


    def __init__(self, *args, **kwargs):
        super(UpdateForm, self).__init__(*args, **kwargs)
        self.fields['comunidad'].required = True
        self.fields['username'].required = True
        self.fields['first_name'].required = True
        self.fields['last_name'].required = True
        self.fields['edad'].required = True
        self.fields['email'].required = True
        

    def clean_username(self):
        username = self.cleaned_data['username']
        validate_rut(username)  # Llama a la función de validación personalizada
        return username
    
class UpdateFormPerfil(ModelForm):
    
    email = forms.CharField(validators=[validators.EmailValidator(message="El correo electrónico debe ser válido.")])
    nueva_contraseña = forms.CharField(max_length=100)
    confirmar_contraseña = forms.CharField(max_length=100)
    class Meta:
        model= User
        fields=['username','first_name','last_name','email',
                'edad','comunidad']
        labels={
            'username':'RUT',
            'first_name':'Nombre',
            'last_name':'Apellido',
            'email':'Correo electrónico',
            'edad':'Edad',
            
        }
        widgets={
            'username':TextInput( 
                attrs={
                    'class':'form-control',
                    'placeholder':'Escriba su rut con el formato: (203627904)'

                }
            ),
            'first_name':TextInput( 
                attrs={
                    'class':'form-control',
                    'placeholder':'Pedro'

                }
            ),
            'last_name':TextInput( 
                attrs={
                    'class':'form-control',
                    'placeholder':'Muñoz'

                }
            ),
            'email':TextInput( 
                attrs={
                    'class':'form-control',
                    'placeholder':'Pedromuñoz@gmail.com'

                }
            )
            
        }


    def __init__(self, *args, **kwargs):
        super(UpdateFormPerfil, self).__init__(*args, **kwargs)
        self.fields['comunidad'].required = True
        self.fields['username'].required = True
        self.fields['first_name'].required = True
        self.fields['last_name'].required = True
        self.fields['edad'].required = True
        self.fields['email'].required = True
        self.fields['confirmar_contraseña'].required = False
        self.fields['nueva_contraseña'].required = False        

    def clean_username(self):
        username = self.cleaned_data['username']
        validate_rut(username)  # Llama a la función de validación personalizada
        return username
    
    def clean(self):
        cleaned_data = super().clean()
        nueva_contraseña = cleaned_data.get("nueva_contraseña")
        confirmar_contraseña = cleaned_data.get("confirmar_contraseña")

        if nueva_contraseña != confirmar_contraseña:
            raise forms.ValidationError("Las contraseñas no coinciden")


class UserFormCRUD(ModelForm):
    ROLES = (
        ('Usuario', 'Usuario'),

moni/crud/templates/usuario/new/newUsuario.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <script src="https://cdn.jsdelivr.net/npm/admin-lte@3.1/dist/js/adminlte.min.js"></script>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet">
    <link rel="icon" href="https://cdn-icons-png.flaticon.com/512/826/826923.png" type="image/png">
    <link rel="stylesheet" href="{% static 'css/interior.css' %}">
    <link rel="stylesheet" href="{% static 'css/nabvar.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css" integrity="sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY=" crossorigin="" />
    <script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js" integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo=" crossorigin=""></script>
    <script src="https://code.jquery.com/jquery-3.7.0.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <title>Crear Habitante</title>
</head>

    <body>
      {% include "barra_lateral_admin.html" %}
      
      <nav class="navbar">
        <img src="https://cdn-ua.hostingreactor.com/ua_www/cache/wp-content/uploads/2020/12/Logo_svg.svg" alt="Logo" class="logo">
          <div class="navbar-left">
              <span class="hidro-tech">HidroTech</span>
          </div>
          <div class="navbar-center">
              <div class="admin-box">Vista Administrador</div>
          </div>
          <a href="{% url 'crud:listauser' %}" class="volverr">Volver</a>
          <a href="{% url 'nucleo:logout' %}" class="cerrar-sesion">Cerrar Sesión</a>
      </nav>
    
    <div class="center-container">
    <div class="vertientes-containerr">
            <div id="formularionew" class="center-div">
              <div class="card-header">
              <h3 class="card-title">Crear Nuevo Habitante</h3>
              </div>
              <form method="post" onsubmit="return enviarFormulario();">
              <div class="card-body">
              <div class="form-group">
                {{ form.errors }}
              {% csrf_token %}
              {% for field in form %}
              <div class="form-group">
                <label for="email">{{ field.label }} :</label>
                {{ field }}
              </div>
              {% endfor %}
              </div>
              </div>
              <div class="card-footer">
              <button type="submit"  class="btn btn-success">Crear</button>
              <a href="{% url 'crud:listauser' %}" class="button">
              <button type="button" class="btn btn-danger">Cancelar</button>
              </a>
              </div>
              </form>
              </div>
      </div>
    </div>
    <script>

    //VALIDACIONES 

    function validarRut(rut) {
  // Eliminar puntos y guiones
  rut = rut.replace(/\./g, "").replace(/-/g, "").toUpperCase();

  // Separar número y dígito verificador
  const numRut = rut.slice(0, -1);
  const dv = rut.slice(-1);

  // Calcular dígito verificador esperado
  let suma = 0;
  let mul = 2;

  for (let i = numRut.length - 1; i >= 0; i--) {
    suma += parseInt(numRut.charAt(i)) * mul;
    mul = mul === 7 ? 2 : mul + 1;
  }

  const resultado = suma % 11 === 0 ? 0 : 11 - (suma % 11);

  // Verificar dígito verificador
  if (resultado === 10 && dv === "K") {
    return true;
  } else if (resultado === parseInt(dv)) {
    return true;
  } else {
    return false;
  }
}

function validarNombre(first_name) {
    var regex = /^[0-9]+$/;
    if (regex.test(first_name)) {
                
                return true;
    }

}
function validarApellido(last_name) {
    var regex = /^[0-9]+$/;
    if (regex.test(last_name)) {
                
                return true;
    }
    
}
function validarEmail(email) {
    var regex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    if (!regex.test(email)) {
                
                return false;
    }
    
}
function comparadorPass(pass1,pass2) {
    
    if (pass1!=pass2) {
                return false;
    }
    
}


 



$("#formularionew").submit(function(evt) {
    
    let rut = $("#id_username").val();
    let first_name = $("#id_first_name").val();
    let last_name = $("#id_last_name").val();
    let email = $("#id_email").val();
    let pass1 = $("#id_password").val();
    let pass2 = $("#id_confirmar_contraseña").val();
    let a=rut.length;
    console.log(a)
    if (rut.length>12 || rut.length<6 ) {
        console.log('EXTENSION')
        evt.preventDefault();
        Swal.fire({
        title: 'RUT invalido',
        text: 'El tamaño del rut no es correcto',
        icon: 'error',
        confirmButtonText: 'Aceptar'
            })

    }
    
    
    const resultado = validarRut(rut);
    const resultado_nombre = validarNombre(first_name);
    const resultado_apellido = validarApellido(last_name);
    const resultado_email = validarEmail(email);
    const comparador = comparadorPass(pass1,pass2);
    
    

    if (resultado==false){
        
            
                evt.preventDefault();
                Swal.fire({
                title: 'RUT invalido',
                text: 'Porfavor, revise el campo',
                icon: 'error',
                confirmButtonText: 'Aceptar'
            })
            
    }
    if (resultado_nombre==true){
            evt.preventDefault();
            
            
            Swal.fire({
            title: 'Nombre invalido',
            text: 'Su nombre no puede contener numeros',
            icon: 'error',
            confirmButtonText: 'Aceptar'
            })
            
    }
    if (resultado_apellido==true){
            evt.preventDefault();
            
            Swal.fire({
            title: 'Apellido invalido',
            text: 'Su apellido no puede contener numeros',
            icon: 'error',
            confirmButtonText: 'Aceptar'
            })
    }
    if (resultado_email==false){
            evt.preventDefault();
            
            Swal.fire({
            title: 'Email invalido',
            text: 'Revise su email',
            icon: 'error',
            confirmButtonText: 'Aceptar'
            })
    }
    if (comparador==false){
            evt.preventDefault();
            
            Swal.fire({
            title: 'Contraseñas no coinciden',
            text: 'Revise sus contraseñas',
            icon: 'error',
            confirmButtonText: 'Aceptar'
            })
    }



            
    
    
});





      
    
      function enviarFormulario() {
        // Verifica si el formulario es válido antes de mostrar el mensaje y enviarlo
        if (document.forms[0].checkValidity()) {
          mostrarMensaje();
          setTimeout(function() {
            document.forms[0].submit();
          }, 2000);
          return false;
        }
        // Si el formulario no es válido, no hagas nada y muestra los errores al usuario
        return false;
      }





</script>
    </body>
</html>

moni/crud/templates/usuario/new/prueba.html
<html>
    <head>
      <script src="https://cdn.jsdelivr.net/npm/admin-lte@3.1/dist/js/adminlte.min.js"></script>
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/admin-lte@3.1/dist/css/adminlte.min.css">
      <link rel="icon" href="https://cdn-icons-png.flaticon.com/512/826/826923.png" type="image/png">

    </head>
    <style>
      .center-div {
        width: 900px; /* Ajusta el ancho según tus necesidades */
        margin: 0 auto; /* Establece margen automático en los lados */
        background-color: rgb(211, 211, 211);
      }
      </style>
    <body>
dssssssssssssss


    </body>
</html>